### Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###  Load datasets

In [2]:
dataset = pd.read_csv("carPrice.csv")
dataset=dataset.drop(['car_ID'], axis=1)
dataset

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

### convert string column to numeric

In [3]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
dataset['fueltype']= label.fit_transform(dataset['fueltype'])
print(dataset)

     symboling                   CarName  fueltype aspiration doornumber  \
0            3        alfa-romero giulia         1        std        two
1            3       alfa-romero stelvio         1        std        two
2            1  alfa-romero Quadrifoglio         1        std        two
3            2               audi 100 ls         1        std       four
4            2                audi 100ls         1        std       four
..         ...                       ...       ...        ...        ...
200         -1           volvo 145e (sw)         1        std       four
201         -1               volvo 144ea         1      turbo       four
202         -1               volvo 244dl         1        std       four
203         -1                 volvo 246         0      turbo       four
204         -1               volvo 264gl         1      turbo       four

         carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0    convertible        rwd          front       88.6      168.8  ...
1    convertible        rwd          front       88.6      168.8  ...
2      hatchback        rwd          front       94.5      171.2  ...
3          sedan        fwd          front       99.8      176.6  ...
4          sedan        4wd          front       99.4      176.6  ...
..           ...        ...            ...        ...        ...  ...
200        sedan        rwd          front      109.1      188.8  ...
201        sedan        rwd          front      109.1      188.8  ...
202        sedan        rwd          front      109.1      188.8  ...
203        sedan        rwd          front      109.1      188.8  ...
204        sedan        rwd          front      109.1      188.8  ...

     enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0           130        mpfi       3.47   2.68              9.0         111
1           130        mpfi       3.47   2.68              9.0         111
2           152        mpfi       2.68   3.47              9.0         154
3           109        mpfi       3.19   3.40             10.0         102
4           136        mpfi       3.19   3.40              8.0         115
..          ...         ...        ...    ...              ...         ...
200         141        mpfi       3.78   3.15              9.5         114
201         141        mpfi       3.78   3.15              8.7         160
202         173        mpfi       3.58   2.87              8.8         134
203         145         idi       3.01   3.40             23.0         106
204         141        mpfi       3.78   3.15              9.5         114

    peakrpm  citympg  highwaympg    price
0      5000       21          27  13495.0
1      5000       21          27  16500.0
2      5000       19          26  16500.0
3      5500       24          30  13950.0
4      5500       18          22  17450.0
..      ...      ...         ...      ...
200    5400       23          28  16845.0
201    5300       19          25  19045.0
202    5500       18          23  21485.0
203    4800       26          27  22470.0
204    5400       19          25  22625.0

[205 rows x 25 columns]

In [ ]:
#dataset['fueltype']=dataset['fueltype'].apply(lambda x: 1 if x=='gas' else 0)
#print(dataset['fueltype'].head(50))

In [ ]:
#carPrice=set(dataset['fueltype'])
#dataset['fueltype']=dataset['fueltype'].map({'diesel': 0, 'gas': 1}).astype(int)
#print(dataset['fueltype'])

### Splitting x & y

In [4]:
Xdata = dataset.drop('price',axis=1)
numcol=Xdata.select_dtypes(exclude=['object']).columns # new syntax to get all numeric column from datasets
X= Xdata[numcol]
X

,symboling,fueltype,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,3,1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,1,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,2,1,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,2,1,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,114,5400,23,28
201,-1,1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,160,5300,19,25
202,-1,1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,134,5500,18,23
203,-1,0,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,106,4800,26,27
204,-1,1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,114,5400,19,25

In [5]:
y =dataset['price']
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

### Scaling the independent variables

In [7]:
from sklearn.preprocessing import scale
cols = X.columns
x =pd.DataFrame(scale(X))
print(x)

           0         1         2         3         4         5         6   \
0    1.743470  0.328798 -1.690772 -0.426521 -0.844782 -2.020417 -0.014566
1    1.743470  0.328798 -1.690772 -0.426521 -0.844782 -2.020417 -0.014566
2    0.133509  0.328798 -0.708596 -0.231513 -0.190566 -0.543527  0.514882
3    0.938490  0.328798  0.173698  0.207256  0.136542  0.235942 -0.420797
4    0.938490  0.328798  0.107110  0.207256  0.230001  0.235942  0.516807
..        ...       ...       ...       ...       ...       ...       ...
200 -1.476452  0.328798  1.721873  1.198549  1.398245  0.728239  0.763241
201 -1.476452  0.328798  1.721873  1.198549  1.351515  0.728239  0.949992
202 -1.476452  0.328798  1.721873  1.198549  1.398245  0.728239  0.878757
203 -1.476452 -3.041381  1.721873  1.198549  1.398245  0.728239  1.273437
204 -1.476452  0.328798  1.721873  1.198549  1.398245  0.728239  0.975021

           7         8         9         10        11        12        13  \
0    0.074449  0.519071 -1.839377 -0.288349  0.174483 -0.262960 -0.646553
1    0.074449  0.519071 -1.839377 -0.288349  0.174483 -0.262960 -0.646553
2    0.604046 -2.404880  0.685946 -0.288349  1.264536 -0.262960 -0.953012
3   -0.431076 -0.517266  0.462183 -0.035973 -0.053668  0.787855 -0.186865
4    0.218885 -0.517266  0.462183 -0.540725  0.275883  0.787855 -1.106241
..        ...       ...       ...       ...       ...       ...       ...
200  0.339248  1.666445 -0.336970 -0.162161  0.250533  0.577692 -0.340094
201  0.339248  1.666445 -0.336970 -0.364062  1.416637  0.367529 -0.953012
202  1.109571  0.926204 -1.232021 -0.338824  0.757535  0.787855 -1.106241
203  0.435538 -1.183483  0.462183  3.244916  0.047732 -0.683286  0.119594
204  0.339248  1.666445 -0.336970 -0.162161  0.250533  0.577692 -0.953012

           14
0   -0.546059
1   -0.546059
2   -0.691627
3   -0.109354
4   -1.273900
..        ...
200 -0.400490
201 -0.837195
202 -1.128332
203 -0.546059
204 -0.837195

[205 rows x 15 columns]

###  Train test split

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X, y, test_size=0.20, random_state=0)

### Training using randomforest regressor

In [11]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

### Evaluate the model

In [12]:
ypred = model.predict(X_test)

from sklearn.metrics import r2_score
r2score = r2_score(y_test, ypred)
print('R2score', r2score*100)

R2score 90.29040839686343